### PR TITLE
get ancestor topics from topic tree

### PR DESCRIPTION
**Pull request by aryam7**
@Maxwellfire needed ancestor TopicTree data. I added another query string parameter to distinguish between the two types of requests
`/tree/data?topic=2&levels=3&direction=up` will give you ancestors
and `/tree/data?topic=2&levels=3&direction=down` will give you descendants

### CODE REVIEW

**Comment by aryam7** [comment]
@Maxwellfire, we can also combine the two types of requests into one, so that you could request something like:
`/tree/data?topic=2&levels_up=3&levels_down=5`

**Comment by Maxwellfire** [comment]
I think combing them into one request would be a good idea. On my end, I use a very similar algorithm to what you use on the back-end to produce a list of nodes that I requested new data for. Then I take the data that you send, and do a merge with the data I already have. Existing nodes are updated, missing ones are added, and ones I have that you didn't send me I delete. This means that doing it all at once is probably easier. 

With two requests I would:
- Make request for parent
- Make request for child
- Merge server data
- Get list of ancestors and of decedents on client
- Merge server's list with clients

With one request I would:
- Make request for parent and child
- Get list of ancestors and of decedents on client
- Merge server's list with clients

**Comment by aryam7** [comment]
Alright! Will do

**Comment by aryam7** [comment]
Alright! I'll put them into one request then

**Comment by Maxwellfire** [comment]
I'm not sure I'm going to be able to review the actual code. I don't know enough about what I'm looking at. 

But the concept and described implementation seem good.

**Pull request merged**
